worker_processes auto;

events {
    worker_connections 1024;
}

rtmp {
    server {
        listen 1935;
        chunk_size 4096;

        application ingest {
            live on;
            record off;
            allow publish all;
            allow play all;
        }

        application matrix {
            live on;
            record off;
            allow publish all;
            allow play all;
        }
    }
}

http {
    server {
        listen 80;

        location / {
            return 200 'streambox rtmp is running';
            add_header Content-Type text/plain;
        }
    }
}
